[workspace]
resolver = "2"
members = ["crates/main"]

[workspace.package]
version = "0.4.0"
edition = "2024"
license = "GPL-3.0-only"
rust-version = "1.95"
authors = ["ARGVUS"]
repository = "https://github.com/argvus/argvus-greeter"
homepage = "https://github.com/argvus/argvus-greeter"
description = "Lightweight GTK4 greetd greeter for the Argvus Desktop Environment"

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
